### ISSUE TITLE
VirusTotal feature - FN

### ISSUE THREAD

**Issue by johnk3r** [Squiblydoo/certReport#1]
hey @Squiblydoo,  thank you very much for this update ❤️!

I tested with SHA256 **c22323ff4c81c5e26eb8925c2ba961dd8b89af01870b42eae013fefb6af96a26**, with the latest version of certReport and I had the following error:

` x509_details = json_python_value["data"]["attributes"]["signature_info"]["x509"][0]
KeyError: 'x509'
`
  
This object does not exist in the VT response for this sample:

` "signature_info": {  
                "verified": "Signed",  
                "signing date": "07:22 PM 07/08/2024",  
                "signers": "ROASTED BEANS PTY LTD; GlobalSign GCC R45 EV CodeSigning CA 2020; GlobalSign Code Signing Root R45",  
                "counter signers details": [  
                    {
                        "status": "Valid",  
                        "valid usage": "Timestamp Signing",  
                        "name": "DigiCert Timestamp 2023",  
                        "algorithm": "sha256RSA",  
                        "valid from": "12:00 AM 07/14/2023",  
                        "valid to": "11:59 PM 10/13/2034",  
                        "serial number": "05 44 AF F3 94 9D 08 39 A6 BF DB 3F 5F E5 61 16",  
                        "cert issuer": "DigiCert Trusted G4 RSA4096 SHA256 TimeStamping CA",  
                        "thumbprint": "66F02B32C2C2C90F825DCEAA8AC9C64F199CCF40"  
                    },  
`

**Comment by Squiblydoo** [comment]
Awesome, glad to hear the update is useful for you.
I'll take a look at that example, that is good to know. (For some reason, I forgot to do much testing and I have a few other issues that need more error handling.)

I'll look into the appropriate solution and hopefully have a fix out within the next few days.

**Comment by Squiblydoo** [comment]
Issue is resolved in 2.0.2. Please use `pip install -U certReport` to update.

The issue was that I shouldn't have been relying on the x509 attribute (I blindly grabbed it because it had the details I wanted) but rather the "signers details" attribute. This has been fixed. 

Note, I have also made it possible to generate reports when there is no certificate too. This is useful in instances such as MSIX files where the certificate is not on the same page as the MSIX hash. 

Changes:
2.0.2
-   Fixed bugs in regards to checking if attributes of the API results exist.
    - Specifically, checking for values like popular threat labels, popular threat names, popular threat categories, crowdsourced IDS rules, were not done appropriately.
-   Fixed bug where report relied on the x509 attribute, which was the wrong attribute to rely on.
-   Improvements:
    -   Made it possible to print a report without a certificate being attached to the file.
    -   Cleaned up printing of IDS rules. Previously, it printed them as a comma separated list, but now it lists them as bullet points.
